name: build

on:
  pull_request:
    branches: [dev, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 가져오기
      - uses: actions/checkout@v4

      # 2) Node 20 & npm 캐시
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3) 의존성 설치
      - run: npm ci

      # 4) 린트 · 타입체크 · 빌드
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build

